# ============================================================
#  lua-server :: MariaDB 11.8 LTS
# ============================================================
[mysqld]
datadir                 = G:/proyectos/lua-server/data/mariadb
port                    = 3306
# Escucha en todas las interfaces para acceso del equipo por LAN.
# El acceso real se controla con el firewall (subred) y con usuarios acotados.
bind-address            = 0.0.0.0
socket                  = G:/proyectos/lua-server/tmp/mysql.sock

character-set-server    = utf8mb4
collation-server        = utf8mb4_unicode_ci
default-storage-engine  = InnoDB

innodb_buffer_pool_size = 256M
innodb_file_per_table   = 1
max_allowed_packet      = 64M
max_connections         = 100
log-error               = G:/proyectos/lua-server/logs/mariadb/error.log
slow_query_log          = 0

# Zona horaria y modo estricto razonable para desarrollo
sql_mode                = STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

[client]
port                    = 3306
socket                  = G:/proyectos/lua-server/tmp/mysql.sock
default-character-set   = utf8mb4

[mysql]
default-character-set   = utf8mb4

